INSERT INTO OBRA (id,descripcion) VALUES (1,'La famosa obra chiquitita');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (1,'ACEPTADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (2,'RECHAZADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (3,'PENDIENTE');
INSERT INTO PRODUCTO (ID,DESCRIPCION,PRECIO) VALUES (1,'El primer producto que creo',1.5);
INSERT INTO PRODUCTO (ID,DESCRIPCION,PRECIO) VALUES (2,'El segundo producto que creo',2.5);
INSERT INTO PRODUCTO (ID,DESCRIPCION,PRECIO) VALUES (3,'El tercer producto que creo',3.5);
INSERT INTO PRODUCTO (ID,DESCRIPCION,PRECIO) VALUES (4,'El cuarto producto que creo',4.5);
