INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (1,'NUEVO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (2,'CONFIRMADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (3,'PENDIENTE');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (4,'CANCELADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (5,'ACEPTADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (6,'RECHAZADO');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (7,'EN PREPARACION');
INSERT INTO ESTADO_PEDIDO (ID_ESTADO_PEDIDO,estado) VALUES (8,'ENTREGADO');