INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION,PRECIO) VALUES (1,'El primer producto',1.0);
INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION,PRECIO) VALUES (2,'El segundo producto',2.0);
INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION,PRECIO) VALUES (3,'El tercer producto',3.0);
INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION,PRECIO) VALUES (4,'El cuarto producto',4.0);